name: xyz_bank
description: "XYZ Bank mobie application."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  intl: ^0.19.0
  firebase_core: ^3.8.0
  firebase_analytics: ^11.3.5
  fluttertoast: ^8.2.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.13
  crypto: ^3.0.6
  dio: ^5.7.0
  flutter_launcher_icons: ^0.13.1
  flutter_markdown: ^0.7.4+1
  flutter_screenutil: ^5.9.3
  go_router: ^14.2.8
  google_fonts: ^6.2.1
  json_annotation: ^4.9.0
  json_serializable: ^6.8.0
  logger: ^2.4.0
  provider: ^6.1.2
  shimmer: ^3.0.0
  url_launcher: ^6.3.1
  webview_flutter: ^4.9.0
  webview_flutter_android: ^3.16.7
  webview_flutter_wkwebview: ^3.15.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/home/
    - assets/images/transfer/
    - google_fonts/
